<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>.All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

/* @var $block \Amasty\Prot\Block\Catalog\Block\Product\View\Type\Select\Multiple */

use Magento\Catalog\Model\Product\Option;

$option = $block->getOption();
$requiredClass = $option->getIsRequire() ? 'required' : '';
$isMultiple = $option->getType() === Option::OPTION_TYPE_MULTIPLE;
$multipleClass = $isMultiple ? '-multiple' : '';
$type = $isMultiple ? 'multiple' : 'default';
$multiNamePart = $isMultiple ? '[]' : '';
?>

<select id="amprot-select_<?= (int)$option->getId() ?>"
        class="amprot-select product-custom-option
               <?= $block->escapeHtmlAttr($requiredClass . ' ' . $multipleClass) ?>"
        name="options[<?= (int)$option->getId() ?>]<?= /* @noEscape */ $multiNamePart ?>"
        data-selector="options[<?= (int)$option->getId() ?>]<?= /* @noEscape */ $multiNamePart ?>"
        data-amprot-js="select-origin_<?= (int)$option->getId() ?>"
        data-option-id="<?= (int) $option->getId() ?>"

        <?php if (!$block->getSkipJsReloadPrice()): ?>
            onchange="opConfig.reloadPrice()"
        <?php endif; ?>

        <?php if ($isMultiple): ?>
            multiple="multiple"
        <?php endif; ?>>

        <?php if (!$isMultiple): ?>
            <option value=""><?= $block->escapeHtml(__('-- Please Select --')) ?></option>
        <?php endif; ?>

        <?php foreach ($option->getValues() as $value): ?>
            <option value="<?= (int)$value->getOptionTypeId() ?>">
                <?= $block->escapeHtml($value->getTitle()) ?>
            </option>
        <?php endforeach;?>
</select>

<div class="amprot-select-block <?= $block->escapeHtmlAttr($multipleClass) ?>"
     data-mage-init='{
         "amprotSelect": {
             "id": "<?= (int)$option->getId() ?>",
             "type": "<?= $block->escapeHtml($type) ?>"
         }
     }'
     data-amprot-js="select">
    <span class="amprot-placeholder" data-amprot-js="placeholder">
        <?= $block->escapeHtml(__('-- Please Select --')) ?>
    </span>
    <ul class="amprot-select-options" data-amprot-js="options">
        <?php $index = 0; ?>
        <?php foreach ($option->getValues() as $value): ?>
            <?php if (($index++) == 0 && !$isMultiple): ?>
                <li class="amprot-option">
                    <?= $block->escapeHtml(__('-- Please Select --')) ?>
                </li>
            <?php endif; ?>
            <li class="amprot-option" data-amprot-js="item" data-amprot-value="<?= (int)$value->getOptionTypeId() ?>">
                <span class="amprot-title"><?= $block->escapeHtml($value->getTitle()) ?></span>
                <span class="amprot-value"><?= $block->escapeHtml($block->getPriceContent($value)) ?></span>
            </li>
        <?php endforeach;?>
    </ul>
</div>

<?php if ($isMultiple): ?>
    <ul class="amprot-tags-block" data-amprot-js="tags"></ul>
<?php endif; ?>
