<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>.All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */
?>
<?php
/** @var \Amasty\Base\Block\Adminhtml\System\Config\InformationBlocks\FeatureRequest $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php if (!$block->isOriginMarketplace()): ?>
    <a href="<?= $escaper->escapeUrl($block->getFeatureRequestLink()) ?>"
       class="ambase-button"
       target="_blank"
       title="<?= $escaper->escapeHtmlAttr(__("Request New Feature")) ?>">
        <?= $escaper->escapeHtml(__("Request New Feature")) ?>
    </a>
<?php endif; ?>
