<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>.All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */
?>
<?php
/** @var \Amasty\Base\Block\Adminhtml\System\Config\InformationBlocks\UserGuide $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php if ($guideLink = $block->getUserGuideLink()): ?>
<div class="amasty-user-guide">
    <span class="message success">
        <?= $escaper->escapeHtml(__('Need help with the settings? Please  consult the')) ?>
        <a target="_blank" href="<?= $escaper->escapeUrl($guideLink) ?>">
            <?= $escaper->escapeHtml(__('user guide')) ?>
        </a>
        <?= $escaper->escapeHtml(__('to configure the extension properly.')) ?>
    </span>
</div>
<?php endif; ?>
