<?php /** @var \Amasty\CronScheduleList\Block\Adminhtml\Notice $block */ ?>

<div class="amasty_cron_notice">
    <div class="message">
        <p>
            <?= /*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>.All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */ /* @escapeNotVerified */
            __('Last Cron Activity: ') . $block->getLastActivity(); ?>
        </p>
    </div>
</div>
