<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>.All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */
?>
<?php
/**
 * @var \Amasty\Base\Block\Import $block
 */
?>
<script>
    require([
            'jquery',
            'Magento_Ui/js/modal/alert',
            'prototype'
        ], function($) {
            //<![CDATA[
            var entity = $('#entity');
            entity.hide();
            entity.closest('fieldset').find('label.label.admin__field-label').css('visibility','hidden');
            $(entity).val('<?= $block->escapeHtml($block->getImportEntity()) ?>');
            varienImport.handleEntityTypeSelector();
            //]]>
        }
    );
</script>
