<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>.All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */
?>
<?php
/** @var \Amasty\Base\Block\Adminhtml\Messages $block */
$messages = $block->getMessages();
?>
<?php if (!empty($messages)): ?>
    <?php foreach ($messages as $message): ?>
        <div class="messages ambase-unsubscribe">
            <div class="message message-success success">
                <div data-ui-id="messages-message-success"><?= /* @noEscape */ $message;?></div>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
