<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>.All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */
?>
<?php
/** @var \Amasty\Base\Block\Adminhtml\Notification $block */
?>
<?php if ($count = $block->getUpdatesCount()): ?>
<style>
    .ambase-tab-container > .admin__page-nav-title:before {
        content: '<?= (int)$count ?>';
    }
</style>
<?php endif; ?>
