<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>.All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\Options\Type\Date */ ?>
<?php $option = $block->getOption() ?>
<?php $optionId = $option->getId() ?>
<?php $class = ($option->getIsRequire()) ? ' required' : ''; ?>
<?php $fieldClass = $class . $block->getParentBlock()->getDependencyClass($option); ?>
<div class="field date<?= /* @escapeNotVerified */ $fieldClass ?>"
     data-mage-init='{"priceOptionDate":{"fromSelector":"#product_addtocart_form"}}'
     data-amprot-js="field">
    <fieldset class="fieldset fieldset-product-options-inner<?= /* @escapeNotVerified */ $class ?>">
        <legend class="legend">
            <span><?= $block->escapeHtml($option->getTitle()) ?></span>
            <?= /* @escapeNotVerified */ $block->getFormattedPrice() ?>
        </legend>
        <div class="control">
            <?php if ($option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_DATE_TIME
                || $option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_DATE): ?>

                <?= $block->getDateHtml() ?>

            <?php endif; ?>

            <?php if ($option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_DATE_TIME
                || $option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_TIME): ?>
                <?= $block->getTimeHtml() ?>
            <?php endif; ?>

            <?php if ($option->getIsRequire()): ?>
                <input type="hidden"
                       name="validate_datetime_<?= /* @escapeNotVerified */ $optionId ?>"
                       class="validate-datetime-<?= /* @escapeNotVerified */ $optionId ?>"
                       value=""
                       data-validate="{'validate-required-datetime':<?= /* @escapeNotVerified */ $optionId ?>}"
                       data-option-id="<?= (int) $optionId ?>" />
            <?php else: ?>
                <input type="hidden"
                       name="validate_datetime_<?= /* @escapeNotVerified */ $optionId ?>"
                       class="validate-datetime-<?= /* @escapeNotVerified */ $optionId ?>"
                       value=""
                       data-validate="{'validate-optional-datetime':<?= /* @escapeNotVerified */ $optionId ?>}"
                       data-option-id="<?= (int) $optionId ?>" />
            <?php endif; ?>
            <script type="text/x-magento-init">
            {
                "#product_addtocart_form": {
                    "validation": {
                        "ignore": ":hidden:not(input[name^='validate_datetime_'])"
                    }
                }
            }
        </script>
        </div>
    </fieldset>

</div>
