<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>.All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

// @codingStandardsIgnoreFile

?>
<?php $_option = $block->getOption() ?>
<div class="field" data-amprot-js="field">
    <label class="label"><span><?= $block->escapeHtml($_option->getTitle()) ?></span></label>
</div>
