<table>
    <tr>
        <th>
            <?= __("Id") ?>
        </th>
        <th>
            <?= __("Title") ?>
        </th>
        <th>
            <?= __("Content") ?>
        </th>
        <th>
            <?= __("Edit") ?>
        </th>
        <th>
            <?= __("Delete") ?>
        </th>
    </tr>
    <?php
    $blogs = $block->getBlogs();

    foreach ($blogs as $blog) { ?>
        <tr>
            <td>
                <?= $blog->getId() ?>
            </td>
            <td>
                <?= $blog->getTitle() ?>
            </td>
            <td>
                <?= substr($blog->getContent(), 0, 20) . '...' ?>
            </td>
            <td>
                <a href="<?= $block->getUrl('blogmanager/manage/edit', ['id' => $blog->getId()]) ?>">
                    <?= __('Edit') ?>
                </a>
            </td>
            <td>
                <a href="<?= $block->getUrl('blogmanager/manage/delete', ['id' => $blog->getId()]) ?>"
                   onclick="return confirm('Are you sure you want to delete this blog?');">
                    <?= __('Delete') ?>
                </a>
            </td>
        </tr>
    <?php } ?>
</table>
